//스크립트 데이터 파일. 배경, 이미지
//name : String, text : String, src : String
const BackgroundsData = [ 
    {// 일상의 영역, 
    //Group NUM : 0
    0 : "images/background/필터/블러/일상/골목길.png",
    1 : "images/background/필터/블러/일상/뉴스.png",
    2 : "images/background/필터/블러/일상/등교길.png",
    3 : "images/background/필터/블러/일상/유성.png",
    4 : "images/background/필터/블러/일상/폴리스라인.png",
    5 : "images/background/필터/블러/일상/호텔로비.png",
    6 : "images/background/필터/블러/일상/호텔룸.png",
    7 : "images/background/필터/블러/일상/교실.png",
    8 : "images/background/필터/블러/일상/블랙배경.png",
    },
    { // 히로인의 영역__공통, 
    //Group NUM : 1
    0 : "images/background/필터/블러/비일상/계단2R.png",
    1 : "images/background/필터/블러/비일상/계단B.png",
    2 : "images/background/필터/블러/비일상/계단R.png",
    3 : "images/background/필터/블러/비일상/꼐블랙 블러.png",
    4 : "images/background/필터/블러/비일상/동굴.png",
    5 : "images/background/필터/블러/비일상/문2R.png",
    6 : "images/background/필터/블러/비일상/문R.png",   
    7 : "images/background/필터/블러/비일상/3F/복도R.png",
    8 : "",
    },
    { // 히로인의 영역__1F, 강당, 보건실, 자료실/창고, 행정실, 
    //Group NUM : 2
    0 : "images/background/필터/블러/비일상/1F/강당R.png",
    1 : "images/background/필터/블러/비일상/1F/보건실R.png",
    2 : "images/background/필터/블러/비일상/1F/자료실2R.png",
    3 : "images/background/필터/블러/비일상/1F/자료실R.png",
    4 : "images/background/필터/블러/비일상/1F/행정B.png",
    5 : "images/background/필터/블러/비일상/1F/행정R.png",
    6 : "",
    7 : "",
    8 : "",
    },
    { // 히로인의 영역__2F 북카페, 컴퓨터실, 급식실, 
    //Group NUM : 3
    0 : "images/background/필터/블러/비일상/2F/급식블러.png",
    1 : "images/background/필터/블러/비일상/2F/급식R.png",
    2 : "images/background/필터/블러/비일상/2F/부엌R.png",
    3 : "images/background/필터/블러/비일상/2F/북카.png",
    4 : "images/background/필터/블러/비일상/2F/북카R.png",
    5 : "",
    6 : "",
    7 : "",
    8 : "",
    },
    { // 히로인의 영역__3F 화장실, 도서실, 과학실, 창있는 복도, 
    //Group NUM : 4
    0 : "images/background/필터/블러/비일상/3F/과학2R.png",
    1 : "images/background/필터/블러/비일상/3F/과학R.png",
    2 : "images/background/필터/블러/비일상/3F/도서관2블러.png",
    3 : "images/background/필터/블러/비일상/3F/도서관R.png",
    4 : "images/background/필터/블러/비일상/3F/화장실1R.png",
    5 : "images/background/필터/블러/비일상/3F/화장실2B.png",
    6 : "images/background/필터/블러/비일상/3F/화장실2R.png",
    7 : "images/background/필터/블러/비일상/3F/화장실3B.png",
    8 : "images/background/필터/블러/비일상/3F/화장실3R.png",
    }
];

const ImageData =   {
    //인물 스탠딩, 자료 스탠딩 파일
    "투명" : "images/charactors/투명.png",
    "히로인_인간_01" : "images/charactors/히로인_인간_01.png",
    "히로인_인간_test" : "images/charactors/히로인_test.png",
    "민재" : "images/charactors/민재_테스트.png",
    "연우" : "images/charactors/연우_test.png",
    "윤호" : "images/charactors/윤호_테스트.png",
    "은주" : "images/charactors/은주_test.png",
    "히로인_인간_02" : "images/charactors/히로인_인간_02.png",
};